/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as UpdatePasswordRouteImport } from './../routes/update-password'
import { Route as ResetPasswordRouteImport } from './../routes/reset-password'
import { Route as ResendVerificationRouteImport } from './../routes/resend-verification'
import { Route as RegisterRouteImport } from './../routes/register'
import { Route as LoginRouteImport } from './../routes/login'
import { Route as AuthenticatedRouteRouteImport } from './../routes/_authenticated/route'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as AuthenticatedWeightChartRouteImport } from './../routes/_authenticated/weight-chart'
import { Route as AuthenticatedProfileRouteImport } from './../routes/_authenticated/profile'
import { Route as AuthenticatedWeightLogIndexRouteImport } from './../routes/_authenticated/weight-log/index'
import { Route as AuthenticatedWeightGoalIndexRouteImport } from './../routes/_authenticated/weight-goal/index'
import { Route as AuthenticatedWeightLogHistoryRouteImport } from './../routes/_authenticated/weight-log/history'
import { Route as AuthenticatedWeightGoalHistoryRouteImport } from './../routes/_authenticated/weight-goal/history'

const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResendVerificationRoute = ResendVerificationRouteImport.update({
  id: '/resend-verification',
  path: '/resend-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWeightChartRoute =
  AuthenticatedWeightChartRouteImport.update({
    id: '/weight-chart',
    path: '/weight-chart',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWeightLogIndexRoute =
  AuthenticatedWeightLogIndexRouteImport.update({
    id: '/weight-log/',
    path: '/weight-log/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWeightGoalIndexRoute =
  AuthenticatedWeightGoalIndexRouteImport.update({
    id: '/weight-goal/',
    path: '/weight-goal/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWeightLogHistoryRoute =
  AuthenticatedWeightLogHistoryRouteImport.update({
    id: '/weight-log/history',
    path: '/weight-log/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWeightGoalHistoryRoute =
  AuthenticatedWeightGoalHistoryRouteImport.update({
    id: '/weight-goal/history',
    path: '/weight-goal/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/resend-verification': typeof ResendVerificationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/update-password': typeof UpdatePasswordRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/weight-chart': typeof AuthenticatedWeightChartRoute
  '/weight-goal/history': typeof AuthenticatedWeightGoalHistoryRoute
  '/weight-log/history': typeof AuthenticatedWeightLogHistoryRoute
  '/weight-goal/': typeof AuthenticatedWeightGoalIndexRoute
  '/weight-log/': typeof AuthenticatedWeightLogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/resend-verification': typeof ResendVerificationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/update-password': typeof UpdatePasswordRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/weight-chart': typeof AuthenticatedWeightChartRoute
  '/weight-goal/history': typeof AuthenticatedWeightGoalHistoryRoute
  '/weight-log/history': typeof AuthenticatedWeightLogHistoryRoute
  '/weight-goal': typeof AuthenticatedWeightGoalIndexRoute
  '/weight-log': typeof AuthenticatedWeightLogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/resend-verification': typeof ResendVerificationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/update-password': typeof UpdatePasswordRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/weight-chart': typeof AuthenticatedWeightChartRoute
  '/_authenticated/weight-goal/history': typeof AuthenticatedWeightGoalHistoryRoute
  '/_authenticated/weight-log/history': typeof AuthenticatedWeightLogHistoryRoute
  '/_authenticated/weight-goal/': typeof AuthenticatedWeightGoalIndexRoute
  '/_authenticated/weight-log/': typeof AuthenticatedWeightLogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/resend-verification'
    | '/reset-password'
    | '/update-password'
    | '/profile'
    | '/weight-chart'
    | '/weight-goal/history'
    | '/weight-log/history'
    | '/weight-goal/'
    | '/weight-log/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/resend-verification'
    | '/reset-password'
    | '/update-password'
    | '/profile'
    | '/weight-chart'
    | '/weight-goal/history'
    | '/weight-log/history'
    | '/weight-goal'
    | '/weight-log'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/resend-verification'
    | '/reset-password'
    | '/update-password'
    | '/_authenticated/profile'
    | '/_authenticated/weight-chart'
    | '/_authenticated/weight-goal/history'
    | '/_authenticated/weight-log/history'
    | '/_authenticated/weight-goal/'
    | '/_authenticated/weight-log/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResendVerificationRoute: typeof ResendVerificationRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resend-verification': {
      id: '/resend-verification'
      path: '/resend-verification'
      fullPath: '/resend-verification'
      preLoaderRoute: typeof ResendVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/weight-chart': {
      id: '/_authenticated/weight-chart'
      path: '/weight-chart'
      fullPath: '/weight-chart'
      preLoaderRoute: typeof AuthenticatedWeightChartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/weight-log/': {
      id: '/_authenticated/weight-log/'
      path: '/weight-log'
      fullPath: '/weight-log/'
      preLoaderRoute: typeof AuthenticatedWeightLogIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/weight-goal/': {
      id: '/_authenticated/weight-goal/'
      path: '/weight-goal'
      fullPath: '/weight-goal/'
      preLoaderRoute: typeof AuthenticatedWeightGoalIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/weight-log/history': {
      id: '/_authenticated/weight-log/history'
      path: '/weight-log/history'
      fullPath: '/weight-log/history'
      preLoaderRoute: typeof AuthenticatedWeightLogHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/weight-goal/history': {
      id: '/_authenticated/weight-goal/history'
      path: '/weight-goal/history'
      fullPath: '/weight-goal/history'
      preLoaderRoute: typeof AuthenticatedWeightGoalHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedWeightChartRoute: typeof AuthenticatedWeightChartRoute
  AuthenticatedWeightGoalHistoryRoute: typeof AuthenticatedWeightGoalHistoryRoute
  AuthenticatedWeightLogHistoryRoute: typeof AuthenticatedWeightLogHistoryRoute
  AuthenticatedWeightGoalIndexRoute: typeof AuthenticatedWeightGoalIndexRoute
  AuthenticatedWeightLogIndexRoute: typeof AuthenticatedWeightLogIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedWeightChartRoute: AuthenticatedWeightChartRoute,
  AuthenticatedWeightGoalHistoryRoute: AuthenticatedWeightGoalHistoryRoute,
  AuthenticatedWeightLogHistoryRoute: AuthenticatedWeightLogHistoryRoute,
  AuthenticatedWeightGoalIndexRoute: AuthenticatedWeightGoalIndexRoute,
  AuthenticatedWeightLogIndexRoute: AuthenticatedWeightLogIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResendVerificationRoute: ResendVerificationRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
