name: CI

on:
  push:
    branches:
      - main
      - develop
      - "feat/**" # Match feature branches (e.g., feature/login, feature/ui)
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Match your Node.js version
          cache: "pnpm"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9 # Match your local pnpm version (e.g., 9.12.2)

      - name: Verify pnpm installation
        run: pnpm --version # Debug: Confirm pnpm is installed

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm lint

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Verify pnpm installation
        run: pnpm --version

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma client
        run: pnpm build # Runs `npx prisma generate && vite build`

      - name: Run Vitest
        run: pnpm test
        env:
          VITE_TRPC_URL: "http://localhost:8888/.netlify/functions/trpc"

  e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Verify pnpm installation
        run: pnpm --version

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: Generate Prisma client
        run: pnpm build

      - name: Run Playwright tests
        run: pnpm test:e2e
        env:
          VITE_TRPC_URL: "http://localhost:8888/.netlify/functions/trpc"

      - name: Upload Playwright report
        if: failure() # Upload report on failure for debugging
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
